config/routes.rb
Rails.application.routes.draw do
  
  resources :events do
    member do
      post 'like'
    end
  end
  devise_for :users

  root 'home#welcome'

end

app/models/event.rb
class Event < ActiveRecord::Base
   belongs_to :user
   has_many :likes
   validate :date_of_event

   def date_of_event
   	  if event_date < Time.now.utc
   	  	errors.add(:event_date, "can't be in the past")
   	  end
   end
end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :user
	belongs_to :event
	validates_uniqueness_of :user_id, :scope => :event_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :events
  has_many :likes
  has_many :liked_events, :through => :likes, :source => :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up)        << :name
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, only: [:show, :edit, :update, :destroy]
  # GET /events
  # GET /events.json
  def index
    @events = current_user.events
    @my_like_events = current_user.liked_events
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    if user_signed_in?
      Like.create(user_id: current_user.id, event_id: params[:id])
      redirect_to events_url
    else
      redirect_to  new_user_session_path , notice: 'Please sign in to express interest'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:event_name, :event_location, :event_date, :user_id)
    end

    def authorize_user
      unless (@event.user == current_user)
        redirect_to events_path, notice: "Unauthorized Access.."
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
  	@events = Event.find_by_sql("select * from events where event_date >= NOW() order by event_date")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_name %><br>
    <%= f.text_field :event_name %>
  </div>
  <div class="field">
    <%= f.label :event_location %><br>
    <%= f.text_field :event_location %>
  </div>
  <div class="field">
    <%= f.label :event_date %><br>
    <%= f.datetime_select :event_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing My Liked Events</h1>

<table>
  <thead>
    <tr>
      <th>Event name</th>
      <th>Event location</th>
      <th>Event date</th>
      <th>User</th>
    </tr>
  </thead>

  <tbody>
    <% @my_like_events.each do |event| %>
      <tr>
        <td><%= event.event_name %></td>
        <td><%= event.event_location %></td>
        <td><%= event.event_date %></td>
        <td><%= event.user.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Event name</th>
      <th>Event location</th>
      <th>Event date</th>
      <th>User</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.event_name %></td>
        <td><%= event.event_location %></td>
        <td><%= event.event_date %></td>
        <td><%= event.user.name %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p>
  <strong>Event name:</strong>
  <%= @event.event_name %>
</p>

<p>
  <strong>Event location:</strong>
  <%= @event.event_location %>
</p>

<p>
  <strong>Event date:</strong>
  <%= @event.event_date %>
</p>

<p>
  <strong>User:</strong>
  <%= @event.user.name%>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/home/welcome.html.erb
<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Event name</th>
      <th>Event location</th>
      <th>Event date</th>
      <th>User</th>
      <th>Express Interest</th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.event_name %></td>
        <td><%= event.event_location %></td>
        <td><%= event.event_date %></td>
        <td><%= event.user.try(:name) %></td>
        <td><%= link_to "Like", like_event_path(event), method: "post" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eventcalendar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= link_to "Home", root_path %> |
  <% if user_signed_in? %>
  <%= link_to 'My Events Page', events_path %> |
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>
  <br/>
  <% if flash[:alert] %>
    <p><%= flash[:alert] %></p>
  <% else %>
    <p id="notice"><%= flash[:notice] %></p>
  <% end %>
<%= yield %>

</body>
</html>